[files]
#These are the image and sound files. If you want to change a file, rename the old one,
#for example, If you have a different nta photo called jimbob.jpg, change images/nta.png to images/jimbob.jpg
nta = images/nta.png
acquire = images/acquire.png
submit1 = images/submit.png
submit2 = images/submit2.png
submit3 = images/submit3.png
submit4 = images/submit4.png
submit5 = images/submit5.png
sound = sounds/sound1.mp3
icon = images/ntaico.png

[positions]
#These are the mouse positions for each button. If they don't work for you,
#take a screenshot of each button type and find the coordinates, then enter them here.
refresh = 92,65
acquire = 115,235
submit = 115,1017

[timing]
#This is where you can tune the delays. Refresh uses its delay twice, once before checking for nta, 
#to make sure the page loaded, and once after, because a 2 second delay between mouse grabs isn't 
#conducive to being able to stop the program. I strongly recommend not going shorter on that.
#Acquire uses a delay only to ensure there's not a false nta call on a long-load refresh.
#Wait is the sleep time in Task mode, you really don't need to do anything with it.
#Submit is the time between timer checks. It can be shrunk, but I wouldn't lengthen it.
refresh = 2
acquire = 0.4
wait = 5
submit = 2

[confidence]
#This is where you can tune how sensitive the image search is. 
#Smaller numbers are more tolerant, while 1 requires an exact match.
#The defaul is .8, which I found to give too many false positives, 
#but 1 did not recognize most of the time. I found .995 to be 
#perfect for most tasks of 7+ minutes.
submit1 = 0.995
submit2 = 0.995
submit3 = 0.990
submit4 = 0.995
submit5 = 0.990
