[files]
#These are the image and sound files. If you want to change a file, rename the old one,
#for example, If you have a different nta photo called jimbob.jpg, change images/nta.png to images/jimbob.jpg
#linux Images:
linux_nta = images/nta.png
linux_acquire = images/linux/acquire.png
linux_acquire2 = images/linux/acquire2.png
linux_acquire3 = images/linux/acquire3.png
linux_submit1 = images/linux/submit.png
linux_submit2 = images/linux/submit2.png
linux_submit3 = images/linux/submit3.png
linux_submit4 = images/linux/submit4.png
linux_submit5 = images/linux/submit5.png

sound = sounds/sound1.mp3
icon = images/ntaico.png

#Winndows 10 images:
win10_nta = images/win10/nta-win.png
win10_acquire = images/win10/avail-win.png
win10_acquire2 = images/win10/acquire2.png
win10_acquire3 = images/win10/acquire3.png
win10_submit1 = images/win10/timer2m-win10.png
win10_submit2 = images/win10/timer6m-win10.png
win10_submit3 = images/win10/timer4-win.png
win10_submit4 = images/win10/timer12m-win10.png
win10_submit5 = images/win10/timer12m2-win10.png

[positions]
#These are the mouse positions for each button. If they don't work for you,
#take a screenshot of each button type and find the coordinates, then enter them here.
refresh = 92,65
acquire = 115,235
acquire2 = 115,289
acquire3 = 115,325
submit = 115,1017
wiggle = -50,-30

[delays]
#This is where you can tune the delays. Refresh uses its delay twice, once before checking for nta, 
#to make sure the page loaded, and once after, because a 2 second delay between mouse grabs isn't 
#conducive to being able to stop the program. I strongly recommend not going shorter on that.
#Refresh is the initial delay to find NTA on the screen, refresh2 is the delay after NTA is found or not 
#found, the shorter the delay, the faster it can click an Acquire if available button. If it's too short, 
#it may not get a chance to recognize the image. Adjust to your internet speed/preference.
#Acquire uses a delay only to ensure there's not a false nta call on a long-load refresh.
#Wait is the sleep time in Task mode, you really don't need to do anything with it.
#Submit is the time between timer checks. It can be shrunk, but I wouldn't lengthen it.
#Wiggle is the time between mouse movements while waiting to auto-submit, if wiggle is turned on 
#in the settings panel.
refresh = 2
refresh2 = 1
acquire = 0.4
wait = 5
submit = 2
wiggle = 120

[confidence]
#This is where you can tune how sensitive the image search is. 
#Smaller numbers are more tolerant, while 1 requires an exact match.
#The default is .8, which I found to give too many false positives, 
#but 1 did not recognize most of the time. I found .995 to be 
#perfect for most tasks of 7+ minutes.
submit1 = 0.995
submit2 = 0.995
submit3 = 0.990
submit4 = 0.995
submit5 = 0.990

[settings]
#These are set in the settings panel, but can also be changed here.
sound_on = True
auto_submit = False
show_threads = False
preferred_door = 1
mouse_move = True
operating_system = Linux
